INSERT INTO public.personal VALUES(120,'ACOSTA ','FABIAN DANIEL','Mantenimiento Electrico');
INSERT INTO public.personal VALUES(971,'ACUÑA','ANGEL RAUL','Pegadora');
INSERT INTO public.personal VALUES(26,'ALZUGARAY','OSCAR LEOPOLDO','Almacenes');
INSERT INTO public.personal VALUES(130,'ARCE','OSVALDO','Almacenes');
INSERT INTO public.personal VALUES(41,'BENITEZ','ALDO JAVIER','Preprensa');
INSERT INTO public.personal VALUES(968,'BILLOUD','CRISTIAN ARIEL','Almacenes');
INSERT INTO public.personal VALUES(963,'BILLOUD','ADRIAN NICOLAS','Almacenes');
INSERT INTO public.personal VALUES(947,'BILLOUD','LUCAS MATIAS','Pegadora');
INSERT INTO public.personal VALUES(988,'BOLGIANI ','JESUS DAVID','Pegadora');
INSERT INTO public.personal VALUES(64,'BRAVO','DANIEL HUGO','Preprensa');
INSERT INTO public.personal VALUES(111,'BROLESE ','FABIO JOAQUIN','Mantenimiento Electrico');
INSERT INTO public.personal VALUES(20,'BRUGNONI','SERGIO DANIEL','Impresión');
INSERT INTO public.personal VALUES(51,'BUSTAMANTE','GUSTAVO FABIAN','Almacenes');
INSERT INTO public.personal VALUES(965,'CAIROLI','FERNANDO DAVID','Tintas');
INSERT INTO public.personal VALUES(138,'CAIROLI','IVAN ALEJANDRO','Administrativo');
INSERT INTO public.personal VALUES(966,'CAIROLI','JAVIER MARCELO','Impresión');
INSERT INTO public.personal VALUES(34,'CAMARA','OSVALDO RAUL','Produccion');
INSERT INTO public.personal VALUES(50,'CAPOBLE','RUBEN DARIO','Almacenes');
INSERT INTO public.personal VALUES(43,'CARDAMONE','JUAN CARLOS','Preprensa');
INSERT INTO public.personal VALUES(8,'CHA','JORGE ALBERTO','Mantenimiento Mec');
INSERT INTO public.personal VALUES(7,'CHIOZZA','OSVALDO DANIEL','Impresión');
INSERT INTO public.personal VALUES(80,'COSTANZO','RUBEN ARISTIDES','Mantenimiento Mec');
INSERT INTO public.personal VALUES(83,'DE MANAS','ANDRES','Produccion');
INSERT INTO public.personal VALUES(942,'DE SANCTIS','MAXIMILIANO','`Descartonaado');
INSERT INTO public.personal VALUES(40,'DIAZ','SERGIO MIGUEL','Informática');
INSERT INTO public.personal VALUES(67,'DIAZ','HECTOR FEDERICO','Descartonado');
INSERT INTO public.personal VALUES(987,'ELGOTAS ','PABLO GABRIEL','Pegadora');
INSERT INTO public.personal VALUES(62,'ESPINOSA','LEONARDO JAVIER','Impresión');
INSERT INTO public.personal VALUES(66,'FERNANDEZ','FEDERICO FRANCISCO','Oficina Tecnica');
INSERT INTO public.personal VALUES(72,'FREYRE','JOSE ADAN','Preprensa');
INSERT INTO public.personal VALUES(13,'FUMIS','DANIEL ANTONIO','Pegadora');
INSERT INTO public.personal VALUES(944,'GONZALEZ','MATIAS','Pegadora');
INSERT INTO public.personal VALUES(945,'GONZALEZ','BRUNO','Pegadora');
INSERT INTO public.personal VALUES(18,'GUITART','SEBASTIAN MIGUEL','Impresión');
INSERT INTO public.personal VALUES(63,'HERNANDO','PABLO EZEQUIEL','Movimientos Internos');
INSERT INTO public.personal VALUES(973,'IEDRO','RICARDO FABIAN','Almacenes');
INSERT INTO public.personal VALUES(136,'INVINKELRIED','JAIRO','Mantenimiento Mec');
INSERT INTO public.personal VALUES(35,'JUNCOS','MIGUEL ANGEL','Troquelado');
INSERT INTO public.personal VALUES(82,'LAGGER','FERNANDO GABRIEL','Impresión');
INSERT INTO public.personal VALUES(71,'LOMAGNO','MIGUEL ANGEL','Pegadora');
INSERT INTO public.personal VALUES(91,'MACEDO ','ADRIAN GONZALO','Impresión');
INSERT INTO public.personal VALUES(146,'MARTINEZ','GUSTAVO','Mantenimiento');
INSERT INTO public.personal VALUES(953,'MAURI','PABLO','Almacenes');
INSERT INTO public.personal VALUES(6,'MAZZOLA','SERGIO HUGO','Mantenimiento Mec');
INSERT INTO public.personal VALUES(90,'MENDIETA','LEOPOLDO MANUEL','Administrativo');
INSERT INTO public.personal VALUES(77,'MENDOZA','DAMIAN','Pegadora');
INSERT INTO public.personal VALUES(57,'MIR','DIEGO DANIEL','Administrativo');
INSERT INTO public.personal VALUES(977,'MONZON','ALEJANDRO ESTEBAN','Pegadora');
INSERT INTO public.personal VALUES(73,'OSUNA','OSCAR MARCELO','Descartonado');
INSERT INTO public.personal VALUES(952,'OSUNA ','ENZO ROBERTO',' Ayud. Gral.');
INSERT INTO public.personal VALUES(93,'OXLEY ','DARIO CESAR','Oficina Tecnica');
INSERT INTO public.personal VALUES(948,'PAVON','JONATAN','Almacenes');
INSERT INTO public.personal VALUES(2,'PEREZLINDO','JORGE MARIO','Impresión');
INSERT INTO public.personal VALUES(28,'PONTONI','EDUARDO GABRIEL','Pegadora');
INSERT INTO public.personal VALUES(36,'PONTONI','GABRIEL ALBERTO','Troquelado');
INSERT INTO public.personal VALUES(52,'RIOS','RUBEN ELVIO','Impresión');
INSERT INTO public.personal VALUES(84,'ROSSO','RODRIGO ARIEL','Administrativo');
INSERT INTO public.personal VALUES(87,'SAAVEDRA','HECTOR EUSEBIO','Descartonado');
INSERT INTO public.personal VALUES(979,'SAAVEDRA','LEANDRO','Troquelado');
INSERT INTO public.personal VALUES(38,'SAMBADE','HORACIO FRANCISCO','Pegadora');
INSERT INTO public.personal VALUES(954,'SCHMITD','MAXIMILIANO','Almacenes');
INSERT INTO public.personal VALUES(10,'TOSONE','ELVIO OMAR','Troquelado');
INSERT INTO public.personal VALUES(100,'VALENZUELA','RAUL ALEJANDRO','Impresión');
INSERT INTO public.personal VALUES(55,'VALLINI','FERNANDO ANIBAL','Administrativo');
INSERT INTO public.personal VALUES(959,'VAZQUEZ','MAXIMILIANO EMANUEL','Enfardado');
INSERT INTO public.personal VALUES(44,'VEGA','HUGO ROBERTO','Pegadora');
INSERT INTO public.personal VALUES(1,'VERCELLI','RUBEN CARLOS','Impresión');

