INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(120,'ACOSTA ','FABIAN DANIEL','Mantenimiento Electrico', '120.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(971,'ACUÑA','ANGEL RAUL','Pegadora', '971.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(26,'ALZUGARAY','OSCAR LEOPOLDO','Almacenes', '26.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(130,'ARCE','OSVALDO','Almacenes', '130.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(41,'BENITEZ','ALDO JAVIER','Preprensa', '41.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(968,'BILLOUD','CRISTIAN ARIEL','Almacenes', '968.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(963,'BILLOUD','ADRIAN NICOLAS','Almacenes', '963.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(947,'BILLOUD','LUCAS MATIAS','Pegadora', '947.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(988,'BOLGIANI ','JESUS DAVID','Pegadora', '988.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(64,'BRAVO','DANIEL HUGO','Preprensa', '64.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(111,'BROLESE ','FABIO JOAQUIN','Mantenimiento Electrico', '111.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(20,'BRUGNONI','SERGIO DANIEL','Impresión', '20.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(51,'BUSTAMANTE','GUSTAVO FABIAN','Almacenes', '51.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(965,'CAIROLI','FERNANDO DAVID','Tintas', '965.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(138,'CAIROLI','IVAN ALEJANDRO','Administrativo', '138.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(966,'CAIROLI','JAVIER MARCELO','Impresión', '966.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(34,'CAMARA','OSVALDO RAUL','Producción', '34.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(50,'CAPOBLE','RUBEN DARIO','Almacenes', '50.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(43,'CARDAMONE','JUAN CARLOS','Preprensa', '43.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(8,'CHA','JORGE ALBERTO','Mantenimiento Mec', '8.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(7,'CHIOZZA','OSVALDO DANIEL','Impresión', '7.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(80,'COSTANZO','RUBEN ARISTIDES','Mantenimiento Mec', '80.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(83,'DE MANAS','ANDRES','Producción', '83.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(942,'DE SANCTIS','MAXIMILIANO','Descartonado', '942.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(40,'DIAZ','SERGIO MIGUEL','Informática', '40.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(67,'DIAZ','HECTOR FEDERICO','Descartonado', '67.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(987,'ELGOTAS ','PABLO GABRIEL','Pegadora', '987.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(62,'ESPINOSA','LEONARDO JAVIER','Impresión', '62.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(66,'FERNANDEZ','FEDERICO FRANCISCO','Oficina Tecnica', '66.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(72,'FREYRE','JOSE ADAN','Preprensa', '72.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(13,'FUMIS','DANIEL ANTONIO','Pegadora', '13.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(944,'GONZALEZ','MATIAS','Pegadora', '944.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(945,'GONZALEZ','BRUNO','Pegadora', '945.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(18,'GUITART','SEBASTIAN MIGUEL','Impresión', '18.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(63,'HERNANDO','PABLO EZEQUIEL','Movimientos Internos', '63.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(973,'IEDRO','RICARDO FABIAN','Almacenes', '973.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(136,'INVINKELRIED','JAIRO','Mantenimiento Mec', '136.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(35,'JUNCOS','MIGUEL ANGEL','Troquelado', '35.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(82,'LAGGER','FERNANDO GABRIEL','Impresión', '82.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(71,'LOMAGNO','MIGUEL ANGEL','Pegadora', '71.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(91,'MACEDO ','ADRIAN GONZALO','Impresión', '91.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(146,'MARTINEZ','GUSTAVO','Mantenimiento', '146.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(953,'MAURI','PABLO','Almacenes', '953.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(6,'MAZZOLA','SERGIO HUGO','Mantenimiento Mec', '6.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(90,'MENDIETA','LEOPOLDO MANUEL','Administrativo', '90.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(77,'MENDOZA','DAMIAN','Pegadora', '77.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(57,'MIR','DIEGO DANIEL','Administrativo', '57.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(977,'MONZON','ALEJANDRO ESTEBAN','Pegadora', '977.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(73,'OSUNA','OSCAR MARCELO','Descartonado', '73.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(952,'OSUNA ','ENZO ROBERTO','Ayud. Gral.', '952.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(93,'OXLEY ','DARIO CESAR','Oficina Tecnica', '93.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(948,'PAVON','JONATAN','Almacenes', '948.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(2,'PEREZLINDO','JORGE MARIO','Impresión', '2.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(28,'PONTONI','EDUARDO GABRIEL','Pegadora', '28.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(36,'PONTONI','GABRIEL ALBERTO','Troquelado', '36.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(52,'RIOS','RUBEN ELVIO','Impresión', '52.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(84,'ROSSO','RODRIGO ARIEL','Administrativo', '84.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(87,'SAAVEDRA','HECTOR EUSEBIO','Descartonado', '87.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(979,'SAAVEDRA','LEANDRO','Troquelado', '979.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(38,'SAMBADE','HORACIO FRANCISCO','Pegadora', '38.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(954,'SCHMITD','MAXIMILIANO','Almacenes', '954.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(10,'TOSONE','ELVIO OMAR','Troquelado', '10.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(100,'VALENZUELA','RAUL ALEJANDRO','Impresión', '100.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(55,'VALLINI','FERNANDO ANIBAL','Administrativo', '55.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(959,'VAZQUEZ','MAXIMILIANO EMANUEL','Enfardado', '959.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(44,'VEGA','HUGO ROBERTO','Pegadora', '44.jpg',true);
INSERT INTO public.personal (nro_legajo,apellido,nombre,sector,imagen,enabled) VALUES(1,'VERCELLI','RUBEN CARLOS','Impresión', '1.jpg',true);


INSERT INTO public.usuario (id_usuario, contraseña, enabled, usuario, nombre, apellido) VALUES(100,'$2a$10$1EF13SS0g4miIVrvtpuxXueo6O0W/nJ5hNee2QqqCEYrxsfFXYLHa',true,'emiii','Emiliano','Mendoza');
INSERT INTO public.roles (id_rol, rol) VALUES(1,'USER');
INSERT INTO public.roles (id_rol, rol) VALUES(2,'ADMIN');
INSERT INTO public.roles (id_rol, rol) VALUES(3,'GUARDIA');
INSERT INTO public.roles (id_rol, rol) VALUES(4,'NOTIFICADOR');
INSERT INTO public.roles (id_rol, rol) VALUES(5,'AUTORIZADOR');

INSERT INTO public.usuario_roles (id_usuario, id_rol) VALUES(100,2);

INSERT INTO public.material VALUES(1,'Nylon');
INSERT INTO public.material VALUES(2,'Cauchos');
INSERT INTO public.material VALUES(3,'Sub cauchos');
INSERT INTO public.material VALUES(4,'Recortes cartulina');
INSERT INTO public.material VALUES(5,'Pliegos malos');
INSERT INTO public.material VALUES(6,'Pallets');
INSERT INTO public.material VALUES(7,'Troquel dado de baja');
INSERT INTO public.material VALUES(8,'Otro');

